# k8s/production/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: langgraph-secrets
  namespace: langgraph-search
type: Opaque
stringData:
  BRAVE_SEARCH_API_KEY: "your-brave-key"
  SERPAPI_API_KEY: "your-serp-key"
  ZENROWS_API_KEY: "your-zenrows-key"
  LANGSMITH_API_KEY: "your-langsmith-key"
  DATABASE_URL: "postgresql://user:pass@postgres:5432/langgraph"
  REDIS_URL: "redis://redis-cluster:6379"
